"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['break-timer.py']
DATA_FILES = ['icons']
OPTIONS = OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'wind.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
